spring:
  application:
    name: code-doc

  datasource:
    url: jdbc:h2:file:./data/testdb;AUTO_SERVER=TRUE

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true


redis:
  hostname: localhost
  port: 6379